spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/blood_treasure?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  forward-headers-strategy: framework

logging:
  level:
    root: WARN

    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
